### ISSUE TITLE
cannot build with preferences plugin and gradle 2.12+

### ISSUE THREAD

**Issue by rburgst** [griffon/griffon#155] opened 2016-04-28 06:58 UTC
ever since upgrading gradle to 2.12 or 2.13 I can no longer build my project

```
/tmp/myapp/griffon-app/services/com/burgstaller/timetracker/prefs/PreferenceService.groovy: 27: unable to resolve class griffon.plugins.preferences.Preference ,  unable to find class for annotation
 @ line 27, column 5.
       @Preference
```

My build script (`build.gradle`)  includes the griffon preferences plugin as documented

```
    griffon 'org.codehaus.griffon.plugins:griffon-preferences-plugin:1.2.0'
```
It works fine when I use 2.11.

I am using griffon 2.6.

**Comment by aalmiray** [comment] 2016-04-28 08:05
Indeed. Gradle 2.12 changed how dependencies are resolved. The problem is the way the `griffon` configuration is resolved by the `griffon` plugin.

Alternatives until we fix this problem:
1. downgrade to Gradle 2.11
2. do not use the `griffon` configuration to resolve plugin dependencies. Declare all dependencies manually, such as explained at http://griffon-plugins.github.io/griffon-preferences-plugin/#_manual

**Comment by rburgst** [comment] 2016-04-29 16:51
Manual configuration works fine. Thanks.

**Closed** 2016-06-11 20:25 UTC
Labels: Bug
