### ISSUE TITLE
Gradle version issues.

### ISSUE THREAD

**Issue by Renlor** [griffon/griffon#68] opened 2015-06-09 20:39 UTC
I updated to the most recent version of gradle groovy and griffon today and ran into the following issues with gradle 2.3 and 2.4.  The test project is a javafx-groovy project, I have not tested any of the other templates to see if there are other issues in addition to the ones listed here.

#### Gradle 2.3 breaks build command.
The build fails at the :signJars step instead of skipping it like in gradle 2.2.1.

```zsh
renlar@Aincrad ~/Code/test % gvm use gradle 2.3

Using gradle version 2.3 in this shell.
renlar@Aincrad ~/Code/test % gradle build
:createDistributionFiles UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:cssToBin SKIPPED
:classes UP-TO-DATE
:jar
:startScripts
:distTar
:distZip
:jfxJar
:jfxSignJar SKIPPED
:jfxCopyLibs
:compilePackageJava UP-TO-DATE
:compilePackageGroovy UP-TO-DATE
:processPackageResources UP-TO-DATE
:packageClasses UP-TO-DATE
:jfxDeploy
:copyJars SKIPPED
:generateJnlp
:signJars FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signJars'.
> : jarsigner returned: 1
```
#### Gradle 2.4 breaks build under all circumstances
It appears there were a number of changes related to how groovy code which contains annotations is built in version 2.4, [2.4 Release Notes] (https://docs.gradle.org/2.4/release-notes#changes-to-groovy-compilation-when-annotation-processors-are-present).  

```zsh
 renlar@Aincrad ~/Code/test % gvm use gradle 2.4

Using gradle version 2.4 in this shell.
renlar@Aincrad ~/Code/test % gradle build
:createDistributionFiles UP-TO-DATE
:compileJava UP-TO-DATE
:compileGroovy
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/home/renlar/Code/test/build/tmp/compileGroovy/groovy-java-stubs/org/example/TestController.java:10: error: TestController does not implement griffon.core.artifact.GriffonController
@griffon.metadata.ArtifactProviderFor(value=griffon.core.artifact.GriffonController.class) public class TestController
                                                                                                  ^
/home/renlar/Code/test/build/tmp/compileGroovy/groovy-java-stubs/org/example/TestModel.java:10: error: TestModel does not implement griffon.core.artifact.GriffonModel
@griffon.metadata.ArtifactProviderFor(value=griffon.core.artifact.GriffonModel.class) public class TestModel
                                                                                             ^
/home/renlar/Code/test/build/tmp/compileGroovy/groovy-java-stubs/org/example/TestView.java:10: error: TestView does not implement griffon.core.artifact.GriffonView
@griffon.metadata.ArtifactProviderFor(value=griffon.core.artifact.GriffonView.class) public class TestView
                                                                                            ^
3 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error

:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Compilation failed; see the compiler error output for details.
```
Let me know if there is anything else you need or and help I can provide.  I will continue to look into both issues and let you know if I find anything.

**Comment by aalmiray** [comment] 2015-06-09 20:43
Gradle 2.4 breaks Griffon due to the recently added APT-on-Groovy-source feature. This is a know problem as reflected by https://discuss.gradle.org/t/how-to-disable-new-annotationprocessor-on-groovy-code-feature/9531/13

**Comment by aalmiray** [comment] 2015-06-09 20:50
Is the signJar task the one from the jnlp plugin? Perhaps @tschulte may know more about this potential issue. What version of the jnlp plugin is used on this build?

**Comment by Renlar** [comment] 2015-06-09 21:02
I am unsure as to where the signJars task is coming into the build, but the test project is simply the template generated by lazybones.

The gradle-jnlp-plugin version is 0.1.0 according to the build.gradle file.

**Comment by aalmiray** [comment] 2015-06-09 21:17
Running "gradle signJars -S" on a freshly created project (griffon-javafx-groovy)  with Gradle 2.2.1 yields an exception too (using default configuration, no keys specified)

    Caused by: : jarsigner returned: 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
        at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
        at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
        at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
        at groovyx.gpars.extra166y.ParallelArrayWithMapping.apply(ParallelArrayWithMapping.java:48)
        at groovyx.gpars.extra166y.ParallelArray.apply(ParallelArray.java:329)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at groovyx.gpars.pa.GParsPoolUtilHelper.eachParallelPA(GParsPoolUtilHelper.groovy:192)
        at groovyx.gpars.GParsPoolUtil.eachParallel(GParsPoolUtil.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:51)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at de.gliderpilot.gradle.jnlp.SignJarsTask$_signJars_closure3.doCall(SignJarsTask.groovy:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
        at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:109)
        at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.access$400(GroovyCategorySupport.java:65)
        at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:249)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.use(DefaultGroovyMethods.java:400)
        at org.codehaus.groovy.runtime.dgm$612.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:99)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
        at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
        at groovyx.gpars.GParsPool$withExistingPool$1.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
        at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
        at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:173)
        at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
        at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        at de.gliderpilot.gradle.jnlp.SignJarsTask.signJars(SignJarsTask.groovy:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 57 more

the jnlp plugin reports the problem. What's interesting is that the signJars task is not executed as part of "gradle build" when run with Gradle 2.2.1.

Also, I think that the JavaFX plugin and the JNLP plugin have an overlap, as the javafxpackager should be enough to generate the required jnlp and signed jars. It may the case that this issue is fixed by removing the jnlp plugin from a javafx based project.

**Comment by Renlar** [comment] 2015-06-09 21:25
Excluding the jnlp plugin does allow the build to succeed and the signJars task is skipped again as in gradle 2.2.1.

**Comment by tschulte** [comment] 2015-06-10 09:02
Starting with Version 0.1.0 the gradle-jnlp-plugin does automatically add a distribution, if the distribution plugin is applied (https://github.com/tschulte/gradle-jnlp-plugin/issues/17). 

It seems, that starting with gradle 2.3 the application plugin does automatically apply the distribution plugin. This results in `./gradlew build` also building the webstart zip.

Currently, in package.gradle of the generated griffon project, the jnlp plugin is always applied AND signJarParams are always set (defaulting to [alias: '', storepass: '']). The jnlp plugin does automatically try do sign the jars, if signJarParams are given. Because of the above, this results in the observed error.

The fix could either be:

```groovy
apply plugin: 'de.gliderpilot.jnlp'

jnlp {
    useVersions = true
    withXml {
        information {
            title project.name
            vendor project.group ?: project.name
        }
        security {
            'all-permissions'()
        }
    }
    if (!project.hasProperty('keyAlias')) signJarParams.alias = project.keyAlias
    if (!project.hasProperty('keystorePwd')) signJarParams.storepass = project.keystorePwd
}
```

or

```groovy
if (!project.hasProperty('keyAlias')) ext.keyAlias = ''
if (!project.hasProperty('keystorePwd')) ext.keystorePwd = ''

if (keyAlias || keystorePwd) {
    apply plugin: 'de.gliderpilot.jnlp'
    jnlp {
        useVersions = true
        withXml {
            information {
                title project.name
                vendor project.group ?: project.name
            }
            security {
                'all-permissions'()
            }
        }
        signJarParams = [alias: keyAlias, storepass: keystorePwd]
    }
}
```

The former will result in generating the webstart zip all the time, but without signed jars as long as no keyAlias and keystorePwd are given. The latter will not generate the webstart zip at all in that case.

**Comment by aalmiray** [comment] 2015-06-10 11:07
@tschulte: thank you for the pointers. I'll update the griffon project templates with this new information :smile:

**Comment by aalmiray** [comment] 2015-06-19 10:44
Skip applying JNLP if keyAlias/keystorePwd are not set  https://github.com/griffon/griffon/commit/1205a390ad611dfd9245cc7b307fc7e3f12ef309

**Comment by aalmiray** [comment] 2015-07-08 20:29
Gradle 2.5 was released today and it includes a fix for https://issues.gradle.org/browse/GRADLE-3300

**Comment by aalmiray** [comment] 2015-07-09 08:30
Just verified that Gradle 2.5 plus recent changes to the templates (1.4.0-SNAPSHOT) fix all mentioned problems.

**Closed by aalmiray** 2015-07-09 08:30 UTC
Labels: Bug

**Comment by nestoring** [comment] 2015-08-07 20:21
Hi Guys

I can see the issue with stil with gradle 2.5:

My Stack:
babun
lazybone 0.8.1
gradle 2.5
gvm 2.4.2


jarsigner returned: 1
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:643)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
        at org.apache.tools.ant.taskdefs.SignJar.signOneJar(SignJar.java:488)
        at org.apache.tools.ant.taskdefs.SignJar.execute(SignJar.java:403)



15:18:50.280 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:signjar] Executing 'C:\Program Files\Java\jdk1.8.0_31\bin\jarsigner.exe' with arguments:
'C:\Tools\babun\workspace\.babun\cygwin\home\nestor.carrasco\demogriffon\jubilee\build\jnlp\lib\jfxrt.jar'
''

The ' characters around the executable and arguments are
not part of the command.
15:18:50.286 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Execute:Java13CommandLauncher: Executing 'C:\Program Files\Java\jdk1.8.0_31\bin\jarsigner.exe' with arguments:
'C:\Tools\babun\workspace\.babun\cygwin\home\nestor.carrasco\demogriffon\jubilee\build\jnlp\lib\jfxrt.jar'
''

The ' characters around the executable and arguments are
not part of the command.
15:18:50.994 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:signjar]
15:18:50.995 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:signjar] Please type jarsigner -help for usage

**Comment by aalmiray** [comment] 2015-08-07 20:25
Please make sure `gradle/package.gradle` looks like this one https://github.com/griffon/griffon/blob/development/templates/griffon-swing-java-templates/templates/griffon-swing-java/gradle/package.gradle

**Comment by nestoring** [comment] 2015-08-07 20:31
Thanks a lot, 
I replaced the package.gradle and works!!.

I had used the template
http://dl.bintray.com/griffon/griffon-lazybones-templates/griffon-javafx-groovy-template-1.3.0.zip

Thanks a lot for your support
