### ISSUE TITLE
AST transformations are no longer applied in latest griffon groovy version

### ISSUE THREAD

**Issue by rburgst** [griffon/griffon#303] opened 2018-11-06 05:48 UTC
* Griffon Version: 2.15.0
* Gradle Version: 4.7 (also tried 4.10.2)

Steps to reproduce

1. create project with lazybones

    ```bash
    lazybones create  griffon-javafx-groovy ast-bug
    ```

2. add validateable plugin to `build.gradle`

    ```groovy
    ...
    dependencies {
       compile "org.codehaus.griffon:griffon-guice:${griffon.version}"
       // add validation plugin
       griffon 'org.codehaus.griffon.plugins:griffon-validation-plugin:2.0.0'
    ```
    
3. add `@griffon.transform.Validateable` AST transformation to the model class 
   as shown in the [plugin guide](http://griffon-plugins.github.io/griffon-validation-plugin/#_the_validatable_ast_transformation)
   
   ```groovy
    @ArtifactProviderFor(GriffonModel)
    @griffon.transform.Validateable
    class AstBugModel {
        @FXObservable String clickCount = "0"
    }
    ```

4. launch the app via 

    ```bash
    ./gradlew run
    ```
    
## Expected 

App runs normally 

## Actual

App crashes with 
```
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.15.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2018-06-01T09:23:01.065+0200
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: 7a518f1303ae26688437516128c295fd02f547c9
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 1.8.0_181 (Oracle Corporation 25.181-b13)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Mac OS X 10.14 x86_64
[JavaFX-Launcher] INFO griffon.util.AnnotationUtils - resource bundle loader class with instance org.codehaus.griffon.runtime.util.ClassResourceBundleLoader@68076fc9 evicted by org.codehaus.griffon.runtime.groovy.util.GroovyScriptResourceBundleLoader@23badcda
[griffon-pool-1-thread-1] INFO griffon.javafx.JavaFXGriffonApplication - Initializing all startup groups: [astBug]
[griffon-pool-1-thread-1] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception. Stacktrace was sanitized. Set System property 'griffon.full.stacktrace' to 'true' for full report.
griffon.exceptions.InstanceNotFoundException: Could not find an instance of type org.example.AstBugModel
        at griffon.javafx.AbstractJavaFXGriffonApplication.startup(AbstractJavaFXGriffonApplication.java:433)
        at griffon.javafx.JavaFXGriffonApplication.lambda$afterStart$0(JavaFXGriffonApplication.java:93)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error notifying InjectionListener org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$$Lambda$57/1832630697@1e158cd1 of org.example.AstBugModel.
 Reason: griffon.exceptions.InstanceMethodInvocationException: An error occurred while invoking instance method org.example.AstBugModel.postConstructInitialization()
  while locating org.example.AstBugModel

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        ... 2 more
Caused by: griffon.exceptions.InstanceMethodInvocationException: An error occurred while invoking instance method org.example.AstBugModel.postConstructInitialization()
        at griffon.util.GriffonClassUtils.lambda$invokeAnnotatedMethod$0(GriffonClassUtils.java:3280)
        at griffon.util.GriffonClassUtils.invokeAnnotatedMethod(GriffonClassUtils.java:3272)
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:131)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:125)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke method evaluate() on null object
        at org.example.AstBugModel.postConstructInitialization(AstBugModel.groovy)
        at griffon.util.GriffonClassUtils.lambda$invokeAnnotatedMethod$0(GriffonClassUtils.java:3276)
        ... 14 more
```

## Sample Repository

* https://github.com/rburgst/griffon-ast-bug

**Comment by aalmiray** [comment] 2018-11-06 09:38
The features provided by `validation` plugin are not designed to be applied to a `GriffonModel`.  The guide recommends creating specialized domain classes that either extends  `AbstractValidateable` or are annotated with  `@Validateable`.

Be aware that you must inject instances instead of instantiating them directly with the `new` keyword.

**Comment by rburgst** [comment] 2018-11-06 09:43
Note that this was just one of the examples, all the other ASTs (OrmLite) don't work either. I upgraded my previously working app from 2.13 and now all ASTs are no longer performed.
I tried to generate the smallest possible sample to show the problem.

**Comment by aalmiray** [comment] 2018-11-06 09:48
I see. At first I thought this could be a problem with the `apt` plugin as the behavior has changed between Gradle releases. However I cloned the example repository linked above, created a domain class as shown in the guide, injected it into the model, invoked its `validate()` method in the controller and got the expected result.

Next I'll try `ormlite`.

**Comment by aalmiray** [comment] 2018-11-06 10:33
I can confirm this bug exists since Griffon `2.13.0`. For a class annotated as

    package org.codehaus.griffon.compile.ormlite.ast.transform

    @griffon.transform.ConnectionSourceAware
    class Foo { }

The generated bytecode looks like

    package org.codehaus.griffon.compile.ormlite.ast.transform;

    import griffon.plugins.ormlite.ConnectionSourceCallback;
    import griffon.plugins.ormlite.ConnectionSourceHandler;
    import griffon.plugins.ormlite.exceptions.RuntimeSQLException;
    import groovy.lang.GroovyObject;
    import groovy.lang.MetaClass;
    import javax.annotation.Nonnull;
    import javax.inject.Inject;
    import org.codehaus.groovy.runtime.callsite.CallSite;

    public class Foo implements ConnectionSourceHandler, GroovyObject {
        @Inject
        private ConnectionSourceHandler this$connectionSourceHandler;

        public Foo() {
            CallSite[] var1 = $getCallSiteArray();
            MetaClass var2 = this.$getStaticMetaClass();
            this.metaClass = var2;
        }

        public void closeConnectionSource(@Nonnull String param0) {
            CallSite[] var2 = $getCallSiteArray();
            var2[0].call(this.this$connectionSourceHandler, param0);
        }

        public void closeConnectionSource() {
            CallSite[] var1 = $getCallSiteArray();
            var1[1].call(this.this$connectionSourceHandler);
        }

        public <R> R withConnectionSource(@Nonnull String param0, @Nonnull ConnectionSourceCallback<R> param1) throws RuntimeSQLException {
            CallSite[] var3 = $getCallSiteArray();
            return var3[2].call(this.this$connectionSourceHandler, param0, param1);
        }

        public <R> R withConnectionSource(@Nonnull ConnectionSourceCallback<R> param0) throws RuntimeSQLException {
            CallSite[] var2 = $getCallSiteArray();
            return var2[3].call(this.this$connectionSourceHandler, param0);
        }
    }

When compiled with Griffon `2.12.0` however the @Inject annotation is missing since `2.13.0`.

**Comment by aalmiray** [comment] 2018-11-06 14:02
Griffon `2.15.1` has been released with a fix for this issue 😄

**Closed** 2018-11-06 14:01 UTC
Labels: Bug

**Comment by rburgst** [comment] 2018-11-07 06:05
works perfectly now. Thanks a lot!
