### ISSUE TITLE
Task publishToMavenLocal fails in master branch

### ISSUE THREAD

**Issue by MarceloRuiz** [griffon/griffon#172] opened 2016-08-22 21:15 UTC
These are the details when trying to run the task with the Gradle Wrapper:

```
./gradlew publishToMavenLocal
Constructor DefaultSourceDirectorySet(String, FileResolver) has been deprecated and is scheduled to be removed in Gradle 3.0
:application-master-pom:copyPom
:application-master-pom:generatePomFileForMavenPomPublication
:application-master-pom:publishMavenPomPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':application-master-pom:publishMavenPomPublicationToMavenLocal'.
> Failed to publish publication 'mavenPom' to repository 'mavenLocal'
   > Invalid publication 'mavenPom': supplied groupId does not match POM file (cannot edit groupId directly in the POM file).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.877 secs
```

**Comment by aalmiray** [comment] 2016-10-09 13:39
Can't reproduce the problem in `master` nor in `development` branches. Gradle wrapper is set to `3.1`.

**Comment by aalmiray** [comment] 2016-11-18 14:45
Can't reproduce with Gradle wrapper set to `3.1`, `master` is at e3e5483

    ------------------------------------------------------------
    Gradle 3.1
    ------------------------------------------------------------

    Build time:   2016-09-19 10:53:53 UTC
    Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

    Groovy:       2.4.7
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
    OS:           Mac OS X 10.10.5 x86_64

**Comment by aalmiray** [comment] 2016-11-30 12:04
Closed as "Can't Reproduce".

**Closed by aalmiray** 2016-11-30 12:04 UTC
Labels: Task
