### ISSUE TITLE
Can't execute default Griffon Application in Intellij

### ISSUE THREAD

**Issue by Nutomic** [griffon/griffon#189] opened 2016-11-29 14:33 UTC
I created a Griffon project with Kotlin and Gradle, using the [getting started guide](http://griffon-framework.org/tutorials/1_getting_started.html), with the command `lazybones create griffon-javafx-kotlin`. 

The project works fine if I run it on the command line, but I can't get it to work in Intellij IDEA (using the communnity edition, 2016.3). My operating system is Kubuntu 16.10.

I did enable annotation processing in Intellij, and here's my run config:
![griffon](https://cloud.githubusercontent.com/assets/1044450/20713559/15aa0f24-b68c-11e6-9bad-45e784654c52.png)

Log output:
```
23:27:00: Executing external task 'run'...
Constructor DefaultSourceDirectorySet(String, FileResolver) has been deprecated and is scheduled to be removed in Gradle 4.0
[versioning] WARNING - the working copy has unstaged or uncommitted changes.
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:compileKotlinAfterJava UP-TO-DATE
:compileGroovy SKIPPED
:processResources UP-TO-DATE
:cssToBin SKIPPED
:classes UP-TO-DATE
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Griffon 2.8.0
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Build: 2016-09-29T15:32:46.577-0500
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Revision: 3beaf9fa69f33dc8529ebb4c58e4fd7b4c61ba73
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - JVM: 1.8.0_111 (Oracle Corporation 25.111-b14)
[JavaFX-Launcher] INFO org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - OS: Linux 4.8.0-28-generic amd64
[JavaFX-Launcher] ERROR org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - An error occurred while initializing the injector
java.lang.reflect.InvocationTargetException
	at griffon.util.GriffonClassUtils.setProperty(Unknown Source)
	at griffon.javafx.JavaFXGriffonApplication.init(Unknown Source)
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.view.WindowManager
	at griffon.javafx.AbstractJavaFXGriffonApplication.getWindowManager(Unknown Source)
	at griffon.javafx.AbstractJavaFXGriffonApplication.setInjector(Unknown Source)
	... 2 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.Configuration
  at org.codehaus.griffon.runtime.javafx.DefaultJavaFXWindowManager.<init>(Unknown Source)
  while locating org.codehaus.griffon.runtime.javafx.DefaultJavaFXWindowManager
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating griffon.core.view.WindowManager

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	... 4 more
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.Configuration
	at griffon.javafx.AbstractJavaFXGriffonApplication.getConfiguration(Unknown Source)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:95)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:92)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 5 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: There are no ResourceBundle resources matching Config
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating java.util.ResourceBundle annotated with @com.google.inject.name.Named(value=applicationResourceBundle)
    for field at org.codehaus.griffon.runtime.core.ResourceBundleConfigurationProvider.resourceBundle(Unknown Source)
  while locating org.codehaus.griffon.runtime.core.ResourceBundleConfigurationProvider
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating griffon.core.Configuration

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	... 24 more
Caused by: java.lang.IllegalArgumentException: There are no ResourceBundle resources matching Config
	at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:119)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:95)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:92)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 25 more
Exception in Application init method
[main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
java.lang.RuntimeException: Exception in Application init method
Caused by: java.lang.reflect.InvocationTargetException
	at griffon.util.GriffonClassUtils.setProperty(Unknown Source)
	at griffon.javafx.JavaFXGriffonApplication.init(Unknown Source)
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.view.WindowManager
	at griffon.javafx.AbstractJavaFXGriffonApplication.getWindowManager(Unknown Source)
	at griffon.javafx.AbstractJavaFXGriffonApplication.setInjector(Unknown Source)
	... 2 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.Configuration
  at org.codehaus.griffon.runtime.javafx.DefaultJavaFXWindowManager.<init>(Unknown Source)
  while locating org.codehaus.griffon.runtime.javafx.DefaultJavaFXWindowManager
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating griffon.core.view.WindowManager

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	... 4 more
Caused by: griffon.exceptions.InstanceNotFoundException: Could not find an instance of type griffon.core.Configuration
	at griffon.javafx.AbstractJavaFXGriffonApplication.getConfiguration(Unknown Source)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:95)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:92)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 5 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: There are no ResourceBundle resources matching Config
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating java.util.ResourceBundle annotated with @com.google.inject.name.Named(value=applicationResourceBundle)
    for field at org.codehaus.griffon.runtime.core.ResourceBundleConfigurationProvider.resourceBundle(Unknown Source)
  while locating org.codehaus.griffon.runtime.core.ResourceBundleConfigurationProvider
  at org.codehaus.griffon.runtime.injection.GuiceInjector$1.handleBinding(Unknown Source)
  while locating griffon.core.Configuration

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	... 24 more
Caused by: java.lang.IllegalArgumentException: There are no ResourceBundle resources matching Config
	at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:119)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:95)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:92)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 25 more
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.203 secs
Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
23:27:07: External task execution finished 'run'.
```

**Comment by aalmiray** [comment] 2016-11-29 15:48
Filed https://youtrack.jetbrains.com/issue/IDEA-164715

**Comment by aalmiray** [comment] 2016-11-30 11:55
JetBrains replied with:

At this time the annotation processing is only supported in Gradle builds. Support for IDEA builds will be added soon. In the mean time, you can use IDEA's new option to always run builds through Gradle.

**Comment by aalmiray** [comment] 2016-11-30 11:59
Resolving as "Not A Bug" on Griffon's side as there's missing behavior in IntelliJ 2016.3. Please follow up on the provided YouTrack ticket 😄

**Closed by aalmiray** 2016-11-30 11:59 UTC
Labels: Not A Bug

**Comment by Nutomic** [comment] 2016-11-30 15:23
To clarify, the Intellij option is called "Delegate IDE build/run actions to gradle".
