### ISSUE TITLE
@PostConstruct is called on Shutdown

### ISSUE THREAD

**Issue by shnplr** [griffon/griffon#123] opened 2015-12-07 05:29 UTC
Griffon 2.5 javafx-groovy

When shutting down the application, classes annotated @ArtifactProviderFor(GriffonService.class) and containing @PostConstruct, which were not previously instantiated are being instantiated by the injector.

e.g. debugger shows: (where MySampleService.init() is annotated @PostConstruct)

init():22, MySampleService {com.mysample}
invokeAnnotatedMethod():50, MethodUtils {org.codehaus.griffon.runtime.injection}
afterInjection():88, GuiceInjectorFactory$2 {org.codehaus.griffon.runtime.injection}
notifyListeners():119, MembersInjectorImpl {com.google.inject.internal}
... {com.google.inject.internal}
close():281, GuiceInjector {org.codehaus.griffon.runtime.injection}
shutdown():397, AbstractJavaFXGriffonApplication {griffon.javafx}

**Comment by shnplr** [comment] 2015-12-07 05:46
I initially thought I might have custom shutdown handler referencing a GriffonService, however I tested by creating a new class (with no usages) and confirmed its init() method is also invoked on shutdown.

package sample
import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor
import javax.annotation.PostConstruct

@ArtifactProviderFor(GriffonService.class)
public class TestService {
    @PostConstruct
    void init() {
        println "TestService.PostConstruct"
    }
}

**Comment by aalmiray** [comment] 2015-12-10 15:40
Hmm that's odd indeed, however I'm unable to reproduce the problem with the following service definition

    package org.example

    import griffon.core.artifact.GriffonService
    import griffon.metadata.ArtifactProviderFor
    import javax.annotation.PostConstruct
    import javax.annotation.PreDestroy

    @ArtifactProviderFor(GriffonService)
    class SampleService {
        @PostConstruct
        void init() {
            println "TestService.PostConstruct"
        }

        @PreDestroy
        void destroy() {
            println "TestService.PreDestroy"
        }
    }

The service is injected in a controller using `@Inject`. Running the application and shutting it down using the quite menu yields the following

    [2015-12-10 16:37:40,538] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Griffon 2.5.0
    [2015-12-10 16:37:40,538] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Build: 2015-12-01T08:16:56.483+0100
    [2015-12-10 16:37:40,538] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - Revision: bf3eccd04dc550561edaf6221bc19659ec877ef2
    [2015-12-10 16:37:40,538] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - JVM: 1.8.0_66 (Oracle Corporation 25.66-b17)
    [2015-12-10 16:37:40,538] [JavaFX-Launcher] INFO  org.codehaus.griffon.runtime.core.DefaultApplicationBootstrapper - OS: Mac OS X 10.10.5 x86_64
    [2015-12-10 16:37:41,183] [pool-2-thread-1] INFO  griffon.javafx.JavaFXGriffonApplication - Initializing all startup groups: [sample]
    TestService.PostConstruct
    [2015-12-10 16:37:44,790] [JavaFX Application Thread] INFO  griffon.javafx.JavaFXGriffonApplication - Shutdown is in process
    TestService.PreDestroy

**Comment by shnplr** [comment] 2015-12-11 03:19
Hi Andres,


What happens if you comment out the @Inject in the controller so that the service @PostConstruct does NOT run at startup?

What I'm seeing is the @PostConstruct is invoked on shutdown - also I did not have a @PreDestroy defined in the service.


Cheers,

Paul


________________________________

**Comment by aalmiray** [comment] 2015-12-11 12:52
I see it now. This is indeed a problem

**Comment by aalmiray** [comment] 2016-01-07 13:14
@shnplr please let me know if the current fix is enough for your current case. Griffon asserts that `@PostConstruct` is called right after injection is performed for every single instance created by the injector (old behavior), and `@PreDestroy` is called when an MVC member is destroyed and also for every other instance created by the injector.

What's missing is the ability to eagerly destroy instances that are no longer needed, for example, say a secondary MVC group defines a dependency on a `Helper` class which is in prototype scope (the default scope). When said MVC group instance is destroyed so should be the `Helper` instance, thus it's `@PreDestroy` must be invoked (if it exists). At this time the `@PreDestroy` of `Helper` will be invoked while shutting down the application only.

Services are guaranteed to work, as long as you annotated them with `@javax.inject.Singleton`.

**Closed** 2016-01-08 11:48 UTC
Labels: Bug
